import { Translations, AccountData } from './types';

export const TRANSLATIONS: Translations = {
  portalTitle: { en: 'PayMaster Portal', ar: 'بوابة الدفع' },
  allAccounts: { en: 'All Accounts', ar: 'جميع الحسابات' },
  overview: { en: 'Overview', ar: 'نظرة عامة' },
  statement: { en: 'Statement', ar: 'كشف الحساب' },
  makePayment: { en: 'Make Payment', ar: 'إجراء دفع' },
  financeSupport: { en: 'Finance Support', ar: 'الدعم المالي' },
  outstandingBalance: { en: 'Outstanding Balance', ar: 'الرصيد المستحق' },
  dueBy: { en: 'Due by', ar: 'مستحق في' },
  amountPaid: { en: 'Amount Paid', ar: 'المبلغ المدفوع' },
  lastPayment: { en: 'Last payment:', ar: 'آخر دفعة:' },
  activeInstallments: { en: 'Active Installments', ar: 'الأقساط النشطة' },
  nextInstallment: { en: 'Next installment:', ar: 'القسط القادم:' },
  payNow: { en: 'Pay Now', ar: 'ادفع الآن' },
  paymentOverview: { en: 'Payment Overview', ar: 'ملخص الدفع' },
  outstandingDetails: { en: 'Outstanding Balance Details', ar: 'تفاصيل الرصيد المستحق' },
  date: { en: 'Date', ar: 'التاريخ' },
  description: { en: 'Description', ar: 'الوصف' },
  dueDate: { en: 'Due Date', ar: 'تاريخ الاستحقاق' },
  amount: { en: 'Amount', ar: 'المبلغ' },
  sponsorName: { en: 'Sponsor Name', ar: 'اسم الراعي' },
  totalSelected: { en: 'Total Selected', ar: 'المجموع المحدد' },
  paySelected: { en: 'Pay Selected Items', ar: 'دفع العناصر المحددة' },
  accountStatement: { en: 'Account Statement', ar: 'كشف حساب' },
  downloadPdf: { en: 'Download PDF', ar: 'تحميل PDF' },
  print: { en: 'Print', ar: 'طباعة' },
  fromDate: { en: 'From Date', ar: 'من تاريخ' },
  toDate: { en: 'To Date', ar: 'إلى تاريخ' },
  generateStatement: { en: 'Generate Statement', ar: 'إنشاء كشف' },
  transactionId: { en: 'Transaction ID', ar: 'رقم المعاملة' },
  debit: { en: 'Debit', ar: 'مدين' },
  credit: { en: 'Credit', ar: 'دائن' },
  balance: { en: 'Balance', ar: 'الرصيد' },
  receipt: { en: 'Receipt', ar: 'الإيصال' },
  paymentDetails: { en: 'Payment Details', ar: 'تفاصيل الدفع' },
  amountToPay: { en: 'Amount to Pay (QAR)', ar: 'المبلغ المستحق (ر.ق)' },
  paymentMethod: { en: 'Payment Method', ar: 'طريقة الدفع' },
  paymentOption: { en: 'Payment Option', ar: 'خيار الدفع' },
  payInFull: { en: 'Pay in Full', ar: 'دفع كامل' },
  payInAdvance: { en: 'Pay in Advance', ar: 'دفع مقدم' },
  payInInstallments: { en: 'Pay in Installments', ar: 'دفع بالأقساط' },
  numberOfInstallments: { en: 'Number of Installments', ar: 'عدد الأقساط' },
  cardNumber: { en: 'Card Number', ar: 'رقم البطاقة' },
  expiryDate: { en: 'Expiry Date', ar: 'تاريخ الانتهاء' },
  cvv: { en: 'CVV', ar: 'رمز التحقق' },
  cardholderName: { en: 'Cardholder Name', ar: 'اسم حامل البطاقة' },
  paymentSummary: { en: 'Payment Summary', ar: 'ملخص الدفع' },
  total: { en: 'Total', ar: 'المجموع' },
  confirmPay: { en: 'Confirm and Pay', ar: 'تأكيد ودفع' },
  securedPayment: { en: 'Secure 256-bit SSL encrypted payment processing', ar: 'معالجة دفع آمنة ومشفرة بـ 256-بت SSL' },
  subject: { en: 'Subject', ar: 'الموضوع' },
  message: { en: 'Message', ar: 'الرسالة' },
  attachment: { en: 'Attachment (Optional)', ar: 'مرفق (اختياري)' },
  chooseFile: { en: 'Choose File', ar: 'اختر ملف' },
  submitRequest: { en: 'Submit Request', ar: 'إرسال الطلب' },
  otherContact: { en: 'Other Ways to Contact Us', ar: 'طرق أخرى للتواصل معنا' },
  email: { en: 'Email', ar: 'البريد الإلكتروني' },
  phone: { en: 'Phone', ar: 'الهاتف' },
  profile: { en: 'Profile', ar: 'الملف الشخصي' },
  logout: { en: 'Logout', ar: 'تسجيل الخروج' },
  success: { en: 'Success!', ar: 'نجاح!' },
  successMsg: { en: 'Your action has been completed successfully.', ar: 'تم إكمال الإجراء بنجاح.' },
  close: { en: 'Close', ar: 'إغلاق' },
  paid: { en: 'Paid', ar: 'مدفوع' },
  outstanding: { en: 'Outstanding', ar: 'مستحق' },
  accessibility: { en: 'Accessibility', ar: 'إمكانية الوصول' },
  textSize: { en: 'Text Size', ar: 'حجم النص' },
  grayscale: { en: 'Grayscale', ar: 'تدرج الرمادي' },
  reset: { en: 'Reset', ar: 'إعادة تعيين' },
  aiAssistant: { en: 'Smart Finance Advisor', ar: 'مستشار مالي ذكي' },
  aiWelcome: { en: 'Hi Khalid! I can help you with your Qatar Foundation payments. How can I assist you today?', ar: 'مرحباً خالد! يمكنني مساعدتك في مدفوعات مؤسسة قطر الخاصة بك. كيف يمكنني خدمتك اليوم؟' },
  typeMessage: { en: 'Type your question...', ar: 'اكتب سؤالك هنا...' },
  aiThinking: { en: 'Thinking...', ar: 'جاري التفكير...' },
};

export const MOCK_ACCOUNTS: { [key: string]: AccountData } = {
  parent: {
    id: 'parent',
    name: 'All Accounts',
    outstanding: 12450.00,
    paid: 5200.00,
    activeInstallments: '2/4',
    items: [
      { id: '1', date: '01/06/2025', desc: 'Tuition Fee - Summer 2025', dueDate: '15/06/2025', amount: 7450.00, sponsor: 'Self-payment' },
      { id: '2', date: '15/05/2025', desc: 'Activity Fee', dueDate: '30/05/2025', amount: 2500.00, sponsor: 'Ministry of Education' },
      { id: '3', date: '01/05/2025', desc: 'Registration Fee', dueDate: '15/05/2025', amount: 2500.00, sponsor: 'Self-payment' }
    ]
  },
  child1: {
    id: 'child1',
    name: 'Fatima',
    outstanding: 6000.00,
    paid: 3000.00,
    activeInstallments: '1/2',
    items: [
      { id: '4', date: '01/06/2025', desc: 'Tuition Fee - Summer 2025', dueDate: '15/06/2025', amount: 4000.00, sponsor: 'Ministry of Education' },
      { id: '5', date: '15/05/2025', desc: 'Activity Fee', dueDate: '30/05/2025', amount: 2000.00, sponsor: 'Self-payment' }
    ]
  },
  child2: {
    id: 'child2',
    name: 'Ali',
    outstanding: 6450.00,
    paid: 2200.00,
    activeInstallments: '1/2',
    items: [
      { id: '6', date: '01/06/2025', desc: 'Tuition Fee - Summer 2025', dueDate: '15/06/2025', amount: 3450.00, sponsor: 'Self-payment' },
      { id: '7', date: '01/05/2025', desc: 'Registration Fee', dueDate: '15/05/2025', amount: 3000.00, sponsor: 'Ministry of Education' }
    ]
  }
};